export const ROLES = ["Commander", "Pilot", "Engineer"] as const;
export type Role = (typeof ROLES)[number];
export type Player = {
  id: string;
  name: string;
  role: Role;
  ready: boolean;
  seenAt: number;
};
export type Mission = {
  startAt: number;
  evaluatedAt: number;
  deadlines: number[];
  hull: number;
  heading: number;
  target: number;
  power: "Balanced" | "Shield" | "Engines";
  shield: "Off" | "Port" | "Starboard";
  heat: number;
  isolated: string | null;
  vented: boolean;
  repairedAt: number | null;
  resetAt: number | null;
  holdSince: (number | null)[];
  completedAt: (number | null)[];
  codeEntered: string;
  authorizedAt: number | null;
  endedAt: number | null;
  result: "victory" | "defeat" | null;
  reason: string | null;
  secrets: {
    headings: number[];
    sectors: ("Port" | "Starboard")[];
    symbols: Record<string, string>;
    broken: string;
    code: string;
  };
};
export type Room = {
  id: string;
  code: string;
  hostId: string;
  revision: number;
  createdAt: number;
  players: Player[];
  blockedPlayers?: string[];
  mission: Mission | null;
  processed: string[];
};
export type Action = { type: string; value?: string | number | boolean };
export type Shared = {
  startAt: number;
  serverNow: number;
  deadlines: number[];
  phase: number;
  hull: number;
  heat?: number;
  completedAt: (number | null)[];
  repairedAt: number | null;
  endedAt: number | null;
  result: Mission["result"];
  reason: string | null;
};
export type Station = {
  heading?: number;
  target?: number;
  engineReady?: boolean;
  codeEntered?: string;
  authorized?: boolean;
  power?: Mission["power"];
  heat?: number;
  isolated?: string | null;
  vented?: boolean;
  symbols?: Record<string, string>;
  headings?: number[];
  sectors?: string[];
  brokenSymbol?: string;
  code?: string;
  shield?: string;
};
export type Snapshot = {
  id: string;
  code: string;
  hostId: string;
  revision: number;
  players: Player[];
  me: string;
  serverNow: number;
  mission: Shared | null;
  station: Station;
};
